const menu = [
  {
    id: 1,
    title: 'Pancakes',
    category: 'breakfast',
    price: 4.99,
    img: './images/item-1.jpeg',
    desc: `Soft-bun, comes with maple syrup, 10 stacks`,
  },
  {
    id: 2,
    title: 'Whopper',
    category: 'lunch',
    price: 6.99,
    img: './images/item-2.jpeg',
    desc: `Double beefs and melted cheese comes with 20 stacks of chicken nuggets`,
  },
  {
    id: 3,
    title: 'Icecream-shake',
    category: 'shakes',
    price: 2.99,
    img: './images/item-3.jpeg',
    desc: `Milkshake deep frozen with added fruit flavours`,
  },
  {
    id: 4,
    title: 'Breakfast',
    category: 'breakfast',
    price: 5.99,
    img: './images/item-4.jpeg',
    desc: 'Walter.Jr"s favourite, eggs and toast with buttered bacon',
  },
  {
    id: 5,
    title: 'Burger',
    category: 'lunch',
    price: 9.99,
    img: './images/item-5.jpeg',
    desc: `5 ft high burger with deep fried egg, tomato slices, lettuce and chicken meat (or beef)`,
  },
  {
    id: 6,
    title: 'Popsicle-shake',
    category: 'shakes',
    price: 10.99,
    img: './images/item-6.jpeg',
    desc: 'Chocolate milkshake deep frozen with many different flavours',
  },
  {
    id: 7,
    title: 'Chicken sandwhich',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: 'Self-explanatory that is, contains chicken and eggs and dairy product related ingredients',
  },
  {
    id: 8,
    title: 'Burger',
    category: 'lunch',
    price: 6.99,
    img: './images/item-8.jpeg',
    desc: 'Normal default burger for average peeps',
  },
];
export default menu;
